module.exports = {
    subject: "Axios",
    start: 1,
    topics: [
"Introduction",
"Installation",
"Configuration",
"RequestConfig",
"ResponseSchema",
"Interceptors",
"ErrorHandling",
"GETRequests",
"POSTRequests",
"PUTRequests",
"PATCHRequests",
"DELETERequests",
"HEADRequests",
"OPTIONSRequests",
"ConcurrentRequests",
"RequestCancellation",
"URLEncoding",
"CustomInstances",
"Defaults",
"Headers",
"Authentication",
"UploadingFiles",
"DownloadingFiles",
"ProgressTracking",
"Timeouts",
"TransformRequest",
"TransformResponse",
"XSFRProtection",
"HTTPAdapter",
"Testing",
"BrowserCompatibility",
"NodeJS",
"React",
"Vue",
"Angular",
"RetryMechanism",
"ThrottlingRequests",
"Logging",
"TypeScriptSupport"
]
};